language: php

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  include:
    - php: 5.3
      dist: precise

before_script:
  # Composer
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script:
  - phpunit;
